import { Router } from "express";
import healthRoutes from "./v1/health.routes.js";
import authRoutes from "./v1/auth.routes.js";
import paymentRoutes from "./v1/payment.routes.js";
import notificationRoutes from "./v1/notification.routes.js";
import inquiryRoutes from "./v1/inquiry.routes.js";
import userRoutes from "./v1/user.routes.js";
import kycRoutes from "./v1/kyc.routes.js";
import holidayRoutes from "./v1/holiday.routes.js";
import accountPlanRoutes from "./v1/accountPlan.routes.js";
import accountRoutes from "./v1/account.routes.js";
import depositRoutes from "./v1/deposit.routes.js";
import transactionRoutes from './v1/transaction.routes.js';
import symbolRoutes from './v1/symbol.routes.js';
import instrumentRoutes from './v1/instrument.routes.js';
import watchlistRoutes from './v1/watchlist.routes.js';
import marketRoutes from './v1/market.routes.js';
import internalTransferRoutes from './v1/internalTransfer.routes.js';
import withdrawalRoutes from "./v1/withdrawal.routes.js";
const router = Router();

router.use("/v1/health", healthRoutes);
router.use("/v1/auth", authRoutes);
router.use("/v1/user", userRoutes);
router.use("/v1/kyc", kycRoutes);
router.use("/v1/account-plans", accountPlanRoutes);
router.use("/v1/accounts", accountRoutes);
router.use("/v1/payment-methods", paymentRoutes);
router.use("/v1/notification", notificationRoutes);
router.use("/v1/inquiry", inquiryRoutes);
router.use("/v1/holidays", holidayRoutes);
router.use("/v1/deposits", depositRoutes); 
router.use('/v1/transactions', transactionRoutes);
router.use('/v1/symbol', symbolRoutes);
router.use('/v1/instrument', instrumentRoutes);
router.use('/v1/watchlist', watchlistRoutes);
router.use('/v1/market', marketRoutes);
router.use('/v1/internal-transfer', internalTransferRoutes);
router.use("/v1/withdrawals", withdrawalRoutes);
export default router;
